//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("StudentManageModel", "FK__CourseSel__StuNu__23BE4960", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClassLibrary1.Student), "CourseSelect", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClassLibrary1.CourseSelect), true)]
[assembly: EdmRelationshipAttribute("StudentManageModel", "FK_CourseSelect_CourseTeach", "CourseTeach", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClassLibrary1.CourseTeach), "CourseSelect", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClassLibrary1.CourseSelect), true)]
[assembly: EdmRelationshipAttribute("StudentManageModel", "FK__CourseTea__TeaNu__1FEDB87C", "Teacher", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClassLibrary1.Teacher), "CourseTeach", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClassLibrary1.CourseTeach), true)]

#endregion

namespace ClassLibrary1
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class StudentManageEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“StudentManageEntities”部分中的连接字符串初始化新 StudentManageEntities 对象。
        /// </summary>
        public StudentManageEntities() : base("name=StudentManageEntities", "StudentManageEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StudentManageEntities 对象。
        /// </summary>
        public StudentManageEntities(string connectionString) : base(connectionString, "StudentManageEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StudentManageEntities 对象。
        /// </summary>
        public StudentManageEntities(EntityConnection connection) : base(connection, "StudentManageEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Course> Course
        {
            get
            {
                if ((_Course == null))
                {
                    _Course = base.CreateObjectSet<Course>("Course");
                }
                return _Course;
            }
        }
        private ObjectSet<Course> _Course;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CourseSelect> CourseSelect
        {
            get
            {
                if ((_CourseSelect == null))
                {
                    _CourseSelect = base.CreateObjectSet<CourseSelect>("CourseSelect");
                }
                return _CourseSelect;
            }
        }
        private ObjectSet<CourseSelect> _CourseSelect;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CourseTeach> CourseTeach
        {
            get
            {
                if ((_CourseTeach == null))
                {
                    _CourseTeach = base.CreateObjectSet<CourseTeach>("CourseTeach");
                }
                return _CourseTeach;
            }
        }
        private ObjectSet<CourseTeach> _CourseTeach;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Manager> Manager
        {
            get
            {
                if ((_Manager == null))
                {
                    _Manager = base.CreateObjectSet<Manager>("Manager");
                }
                return _Manager;
            }
        }
        private ObjectSet<Manager> _Manager;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Student> Student
        {
            get
            {
                if ((_Student == null))
                {
                    _Student = base.CreateObjectSet<Student>("Student");
                }
                return _Student;
            }
        }
        private ObjectSet<Student> _Student;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Teacher> Teacher
        {
            get
            {
                if ((_Teacher == null))
                {
                    _Teacher = base.CreateObjectSet<Teacher>("Teacher");
                }
                return _Teacher;
            }
        }
        private ObjectSet<Teacher> _Teacher;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Course EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToCourse(Course course)
        {
            base.AddObject("Course", course);
        }
    
        /// <summary>
        /// 用于向 CourseSelect EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToCourseSelect(CourseSelect courseSelect)
        {
            base.AddObject("CourseSelect", courseSelect);
        }
    
        /// <summary>
        /// 用于向 CourseTeach EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToCourseTeach(CourseTeach courseTeach)
        {
            base.AddObject("CourseTeach", courseTeach);
        }
    
        /// <summary>
        /// 用于向 Manager EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToManager(Manager manager)
        {
            base.AddObject("Manager", manager);
        }
    
        /// <summary>
        /// 用于向 Student EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToStudent(Student student)
        {
            base.AddObject("Student", student);
        }
    
        /// <summary>
        /// 用于向 Teacher EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTeacher(Teacher teacher)
        {
            base.AddObject("Teacher", teacher);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentManageModel", Name="Course")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Course : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Course 对象。
        /// </summary>
        /// <param name="crsNum">CrsNum 属性的初始值。</param>
        /// <param name="crsName">CrsName 属性的初始值。</param>
        /// <param name="crsType">CrsType 属性的初始值。</param>
        public static Course CreateCourse(global::System.String crsNum, global::System.String crsName, global::System.String crsType)
        {
            Course course = new Course();
            course.CrsNum = crsNum;
            course.CrsName = crsName;
            course.CrsType = crsType;
            return course;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CrsNum
        {
            get
            {
                return _CrsNum;
            }
            set
            {
                if (_CrsNum != value)
                {
                    OnCrsNumChanging(value);
                    ReportPropertyChanging("CrsNum");
                    _CrsNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CrsNum");
                    OnCrsNumChanged();
                }
            }
        }
        private global::System.String _CrsNum;
        partial void OnCrsNumChanging(global::System.String value);
        partial void OnCrsNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CrsName
        {
            get
            {
                return _CrsName;
            }
            set
            {
                OnCrsNameChanging(value);
                ReportPropertyChanging("CrsName");
                _CrsName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CrsName");
                OnCrsNameChanged();
            }
        }
        private global::System.String _CrsName;
        partial void OnCrsNameChanging(global::System.String value);
        partial void OnCrsNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CrsType
        {
            get
            {
                return _CrsType;
            }
            set
            {
                OnCrsTypeChanging(value);
                ReportPropertyChanging("CrsType");
                _CrsType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CrsType");
                OnCrsTypeChanged();
            }
        }
        private global::System.String _CrsType;
        partial void OnCrsTypeChanging(global::System.String value);
        partial void OnCrsTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentManageModel", Name="CourseSelect")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CourseSelect : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 CourseSelect 对象。
        /// </summary>
        /// <param name="stuNum">StuNum 属性的初始值。</param>
        /// <param name="teaNum">TeaNum 属性的初始值。</param>
        /// <param name="crsNum">CrsNum 属性的初始值。</param>
        /// <param name="schoolYear">SchoolYear 属性的初始值。</param>
        /// <param name="semester">Semester 属性的初始值。</param>
        public static CourseSelect CreateCourseSelect(global::System.String stuNum, global::System.String teaNum, global::System.String crsNum, global::System.DateTime schoolYear, global::System.Int32 semester)
        {
            CourseSelect courseSelect = new CourseSelect();
            courseSelect.StuNum = stuNum;
            courseSelect.TeaNum = teaNum;
            courseSelect.CrsNum = crsNum;
            courseSelect.SchoolYear = schoolYear;
            courseSelect.Semester = semester;
            return courseSelect;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StuNum
        {
            get
            {
                return _StuNum;
            }
            set
            {
                if (_StuNum != value)
                {
                    OnStuNumChanging(value);
                    ReportPropertyChanging("StuNum");
                    _StuNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("StuNum");
                    OnStuNumChanged();
                }
            }
        }
        private global::System.String _StuNum;
        partial void OnStuNumChanging(global::System.String value);
        partial void OnStuNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TeaNum
        {
            get
            {
                return _TeaNum;
            }
            set
            {
                OnTeaNumChanging(value);
                ReportPropertyChanging("TeaNum");
                _TeaNum = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TeaNum");
                OnTeaNumChanged();
            }
        }
        private global::System.String _TeaNum;
        partial void OnTeaNumChanging(global::System.String value);
        partial void OnTeaNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CrsNum
        {
            get
            {
                return _CrsNum;
            }
            set
            {
                if (_CrsNum != value)
                {
                    OnCrsNumChanging(value);
                    ReportPropertyChanging("CrsNum");
                    _CrsNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CrsNum");
                    OnCrsNumChanged();
                }
            }
        }
        private global::System.String _CrsNum;
        partial void OnCrsNumChanging(global::System.String value);
        partial void OnCrsNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SchoolYear
        {
            get
            {
                return _SchoolYear;
            }
            set
            {
                if (_SchoolYear != value)
                {
                    OnSchoolYearChanging(value);
                    ReportPropertyChanging("SchoolYear");
                    _SchoolYear = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SchoolYear");
                    OnSchoolYearChanged();
                }
            }
        }
        private global::System.DateTime _SchoolYear;
        partial void OnSchoolYearChanging(global::System.DateTime value);
        partial void OnSchoolYearChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Semester
        {
            get
            {
                return _Semester;
            }
            set
            {
                if (_Semester != value)
                {
                    OnSemesterChanging(value);
                    ReportPropertyChanging("Semester");
                    _Semester = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Semester");
                    OnSemesterChanged();
                }
            }
        }
        private global::System.Int32 _Semester;
        partial void OnSemesterChanging(global::System.Int32 value);
        partial void OnSemesterChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Grade
        {
            get
            {
                return _Grade;
            }
            set
            {
                OnGradeChanging(value);
                ReportPropertyChanging("Grade");
                _Grade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Grade");
                OnGradeChanged();
            }
        }
        private Nullable<global::System.Decimal> _Grade;
        partial void OnGradeChanging(Nullable<global::System.Decimal> value);
        partial void OnGradeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Selecting
        {
            get
            {
                return _Selecting;
            }
            set
            {
                OnSelectingChanging(value);
                ReportPropertyChanging("Selecting");
                _Selecting = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Selecting");
                OnSelectingChanged();
            }
        }
        private Nullable<global::System.Boolean> _Selecting;
        partial void OnSelectingChanging(Nullable<global::System.Boolean> value);
        partial void OnSelectingChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentManageModel", "FK__CourseSel__StuNu__23BE4960", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("StudentManageModel.FK__CourseSel__StuNu__23BE4960", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("StudentManageModel.FK__CourseSel__StuNu__23BE4960", "Student").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("StudentManageModel.FK__CourseSel__StuNu__23BE4960", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("StudentManageModel.FK__CourseSel__StuNu__23BE4960", "Student", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentManageModel", "FK_CourseSelect_CourseTeach", "CourseTeach")]
        public CourseTeach CourseTeach
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CourseTeach>("StudentManageModel.FK_CourseSelect_CourseTeach", "CourseTeach").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CourseTeach>("StudentManageModel.FK_CourseSelect_CourseTeach", "CourseTeach").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CourseTeach> CourseTeachReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CourseTeach>("StudentManageModel.FK_CourseSelect_CourseTeach", "CourseTeach");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CourseTeach>("StudentManageModel.FK_CourseSelect_CourseTeach", "CourseTeach", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentManageModel", Name="CourseTeach")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CourseTeach : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 CourseTeach 对象。
        /// </summary>
        /// <param name="teaNum">TeaNum 属性的初始值。</param>
        /// <param name="crsNum">CrsNum 属性的初始值。</param>
        /// <param name="schoolYear">SchoolYear 属性的初始值。</param>
        /// <param name="semester">Semester 属性的初始值。</param>
        public static CourseTeach CreateCourseTeach(global::System.String teaNum, global::System.String crsNum, global::System.DateTime schoolYear, global::System.Int32 semester)
        {
            CourseTeach courseTeach = new CourseTeach();
            courseTeach.TeaNum = teaNum;
            courseTeach.CrsNum = crsNum;
            courseTeach.SchoolYear = schoolYear;
            courseTeach.Semester = semester;
            return courseTeach;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TeaNum
        {
            get
            {
                return _TeaNum;
            }
            set
            {
                if (_TeaNum != value)
                {
                    OnTeaNumChanging(value);
                    ReportPropertyChanging("TeaNum");
                    _TeaNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TeaNum");
                    OnTeaNumChanged();
                }
            }
        }
        private global::System.String _TeaNum;
        partial void OnTeaNumChanging(global::System.String value);
        partial void OnTeaNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CrsNum
        {
            get
            {
                return _CrsNum;
            }
            set
            {
                if (_CrsNum != value)
                {
                    OnCrsNumChanging(value);
                    ReportPropertyChanging("CrsNum");
                    _CrsNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CrsNum");
                    OnCrsNumChanged();
                }
            }
        }
        private global::System.String _CrsNum;
        partial void OnCrsNumChanging(global::System.String value);
        partial void OnCrsNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SchoolYear
        {
            get
            {
                return _SchoolYear;
            }
            set
            {
                if (_SchoolYear != value)
                {
                    OnSchoolYearChanging(value);
                    ReportPropertyChanging("SchoolYear");
                    _SchoolYear = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SchoolYear");
                    OnSchoolYearChanged();
                }
            }
        }
        private global::System.DateTime _SchoolYear;
        partial void OnSchoolYearChanging(global::System.DateTime value);
        partial void OnSchoolYearChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Semester
        {
            get
            {
                return _Semester;
            }
            set
            {
                if (_Semester != value)
                {
                    OnSemesterChanging(value);
                    ReportPropertyChanging("Semester");
                    _Semester = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Semester");
                    OnSemesterChanged();
                }
            }
        }
        private global::System.Int32 _Semester;
        partial void OnSemesterChanging(global::System.Int32 value);
        partial void OnSemesterChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Classes
        {
            get
            {
                return _Classes;
            }
            set
            {
                OnClassesChanging(value);
                ReportPropertyChanging("Classes");
                _Classes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Classes");
                OnClassesChanged();
            }
        }
        private Nullable<global::System.Int32> _Classes;
        partial void OnClassesChanging(Nullable<global::System.Int32> value);
        partial void OnClassesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SelectedCount
        {
            get
            {
                return _SelectedCount;
            }
            set
            {
                OnSelectedCountChanging(value);
                ReportPropertyChanging("SelectedCount");
                _SelectedCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SelectedCount");
                OnSelectedCountChanged();
            }
        }
        private Nullable<global::System.Int32> _SelectedCount;
        partial void OnSelectedCountChanging(Nullable<global::System.Int32> value);
        partial void OnSelectedCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SelectedCountMax
        {
            get
            {
                return _SelectedCountMax;
            }
            set
            {
                OnSelectedCountMaxChanging(value);
                ReportPropertyChanging("SelectedCountMax");
                _SelectedCountMax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SelectedCountMax");
                OnSelectedCountMaxChanged();
            }
        }
        private Nullable<global::System.Int32> _SelectedCountMax;
        partial void OnSelectedCountMaxChanging(Nullable<global::System.Int32> value);
        partial void OnSelectedCountMaxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Start
        {
            get
            {
                return _Start;
            }
            set
            {
                OnStartChanging(value);
                ReportPropertyChanging("Start");
                _Start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Start");
                OnStartChanged();
            }
        }
        private Nullable<global::System.Boolean> _Start;
        partial void OnStartChanging(Nullable<global::System.Boolean> value);
        partial void OnStartChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Selecting
        {
            get
            {
                return _Selecting;
            }
            set
            {
                OnSelectingChanging(value);
                ReportPropertyChanging("Selecting");
                _Selecting = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Selecting");
                OnSelectingChanged();
            }
        }
        private Nullable<global::System.Boolean> _Selecting;
        partial void OnSelectingChanging(Nullable<global::System.Boolean> value);
        partial void OnSelectingChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentManageModel", "FK_CourseSelect_CourseTeach", "CourseSelect")]
        public EntityCollection<CourseSelect> CourseSelect
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CourseSelect>("StudentManageModel.FK_CourseSelect_CourseTeach", "CourseSelect");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CourseSelect>("StudentManageModel.FK_CourseSelect_CourseTeach", "CourseSelect", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentManageModel", "FK__CourseTea__TeaNu__1FEDB87C", "Teacher")]
        public Teacher Teacher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("StudentManageModel.FK__CourseTea__TeaNu__1FEDB87C", "Teacher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("StudentManageModel.FK__CourseTea__TeaNu__1FEDB87C", "Teacher").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Teacher> TeacherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("StudentManageModel.FK__CourseTea__TeaNu__1FEDB87C", "Teacher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Teacher>("StudentManageModel.FK__CourseTea__TeaNu__1FEDB87C", "Teacher", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentManageModel", Name="Manager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Manager : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Manager 对象。
        /// </summary>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="userPassword">UserPassword 属性的初始值。</param>
        public static Manager CreateManager(global::System.String userName, global::System.String userPassword)
        {
            Manager manager = new Manager();
            manager.UserName = userName;
            manager.UserPassword = userPassword;
            return manager;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserPassword
        {
            get
            {
                return _UserPassword;
            }
            set
            {
                OnUserPasswordChanging(value);
                ReportPropertyChanging("UserPassword");
                _UserPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserPassword");
                OnUserPasswordChanged();
            }
        }
        private global::System.String _UserPassword;
        partial void OnUserPasswordChanging(global::System.String value);
        partial void OnUserPasswordChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentManageModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Student 对象。
        /// </summary>
        /// <param name="stuNum">StuNum 属性的初始值。</param>
        /// <param name="stuName">StuName 属性的初始值。</param>
        /// <param name="stuGender">StuGender 属性的初始值。</param>
        /// <param name="stuAge">StuAge 属性的初始值。</param>
        /// <param name="stuPhoto">StuPhoto 属性的初始值。</param>
        public static Student CreateStudent(global::System.String stuNum, global::System.String stuName, global::System.String stuGender, global::System.Int32 stuAge, global::System.String stuPhoto)
        {
            Student student = new Student();
            student.StuNum = stuNum;
            student.StuName = stuName;
            student.StuGender = stuGender;
            student.StuAge = stuAge;
            student.StuPhoto = stuPhoto;
            return student;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StuNum
        {
            get
            {
                return _StuNum;
            }
            set
            {
                if (_StuNum != value)
                {
                    OnStuNumChanging(value);
                    ReportPropertyChanging("StuNum");
                    _StuNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("StuNum");
                    OnStuNumChanged();
                }
            }
        }
        private global::System.String _StuNum;
        partial void OnStuNumChanging(global::System.String value);
        partial void OnStuNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StuName
        {
            get
            {
                return _StuName;
            }
            set
            {
                OnStuNameChanging(value);
                ReportPropertyChanging("StuName");
                _StuName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StuName");
                OnStuNameChanged();
            }
        }
        private global::System.String _StuName;
        partial void OnStuNameChanging(global::System.String value);
        partial void OnStuNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StuGender
        {
            get
            {
                return _StuGender;
            }
            set
            {
                OnStuGenderChanging(value);
                ReportPropertyChanging("StuGender");
                _StuGender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StuGender");
                OnStuGenderChanged();
            }
        }
        private global::System.String _StuGender;
        partial void OnStuGenderChanging(global::System.String value);
        partial void OnStuGenderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StuAge
        {
            get
            {
                return _StuAge;
            }
            set
            {
                OnStuAgeChanging(value);
                ReportPropertyChanging("StuAge");
                _StuAge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StuAge");
                OnStuAgeChanged();
            }
        }
        private global::System.Int32 _StuAge;
        partial void OnStuAgeChanging(global::System.Int32 value);
        partial void OnStuAgeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StuPhoto
        {
            get
            {
                return _StuPhoto;
            }
            set
            {
                OnStuPhotoChanging(value);
                ReportPropertyChanging("StuPhoto");
                _StuPhoto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StuPhoto");
                OnStuPhotoChanged();
            }
        }
        private global::System.String _StuPhoto;
        partial void OnStuPhotoChanging(global::System.String value);
        partial void OnStuPhotoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StuSchoolStartDate
        {
            get
            {
                return _StuSchoolStartDate;
            }
            set
            {
                OnStuSchoolStartDateChanging(value);
                ReportPropertyChanging("StuSchoolStartDate");
                _StuSchoolStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StuSchoolStartDate");
                OnStuSchoolStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StuSchoolStartDate;
        partial void OnStuSchoolStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStuSchoolStartDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StuPassword
        {
            get
            {
                return _StuPassword;
            }
            set
            {
                OnStuPasswordChanging(value);
                ReportPropertyChanging("StuPassword");
                _StuPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StuPassword");
                OnStuPasswordChanged();
            }
        }
        private global::System.String _StuPassword;
        partial void OnStuPasswordChanging(global::System.String value);
        partial void OnStuPasswordChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentManageModel", "FK__CourseSel__StuNu__23BE4960", "CourseSelect")]
        public EntityCollection<CourseSelect> CourseSelect
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CourseSelect>("StudentManageModel.FK__CourseSel__StuNu__23BE4960", "CourseSelect");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CourseSelect>("StudentManageModel.FK__CourseSel__StuNu__23BE4960", "CourseSelect", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentManageModel", Name="Teacher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Teacher : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Teacher 对象。
        /// </summary>
        /// <param name="teaNum">TeaNum 属性的初始值。</param>
        /// <param name="teaName">TeaName 属性的初始值。</param>
        /// <param name="teaGender">TeaGender 属性的初始值。</param>
        /// <param name="teaAge">TeaAge 属性的初始值。</param>
        public static Teacher CreateTeacher(global::System.String teaNum, global::System.String teaName, global::System.String teaGender, global::System.Int32 teaAge)
        {
            Teacher teacher = new Teacher();
            teacher.TeaNum = teaNum;
            teacher.TeaName = teaName;
            teacher.TeaGender = teaGender;
            teacher.TeaAge = teaAge;
            return teacher;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TeaNum
        {
            get
            {
                return _TeaNum;
            }
            set
            {
                if (_TeaNum != value)
                {
                    OnTeaNumChanging(value);
                    ReportPropertyChanging("TeaNum");
                    _TeaNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TeaNum");
                    OnTeaNumChanged();
                }
            }
        }
        private global::System.String _TeaNum;
        partial void OnTeaNumChanging(global::System.String value);
        partial void OnTeaNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TeaName
        {
            get
            {
                return _TeaName;
            }
            set
            {
                OnTeaNameChanging(value);
                ReportPropertyChanging("TeaName");
                _TeaName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TeaName");
                OnTeaNameChanged();
            }
        }
        private global::System.String _TeaName;
        partial void OnTeaNameChanging(global::System.String value);
        partial void OnTeaNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TeaGender
        {
            get
            {
                return _TeaGender;
            }
            set
            {
                OnTeaGenderChanging(value);
                ReportPropertyChanging("TeaGender");
                _TeaGender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TeaGender");
                OnTeaGenderChanged();
            }
        }
        private global::System.String _TeaGender;
        partial void OnTeaGenderChanging(global::System.String value);
        partial void OnTeaGenderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeaAge
        {
            get
            {
                return _TeaAge;
            }
            set
            {
                OnTeaAgeChanging(value);
                ReportPropertyChanging("TeaAge");
                _TeaAge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TeaAge");
                OnTeaAgeChanged();
            }
        }
        private global::System.Int32 _TeaAge;
        partial void OnTeaAgeChanging(global::System.Int32 value);
        partial void OnTeaAgeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeaPhoto
        {
            get
            {
                return _TeaPhoto;
            }
            set
            {
                OnTeaPhotoChanging(value);
                ReportPropertyChanging("TeaPhoto");
                _TeaPhoto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TeaPhoto");
                OnTeaPhotoChanged();
            }
        }
        private global::System.String _TeaPhoto;
        partial void OnTeaPhotoChanging(global::System.String value);
        partial void OnTeaPhotoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TeaWorkYear
        {
            get
            {
                return _TeaWorkYear;
            }
            set
            {
                OnTeaWorkYearChanging(value);
                ReportPropertyChanging("TeaWorkYear");
                _TeaWorkYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TeaWorkYear");
                OnTeaWorkYearChanged();
            }
        }
        private Nullable<global::System.DateTime> _TeaWorkYear;
        partial void OnTeaWorkYearChanging(Nullable<global::System.DateTime> value);
        partial void OnTeaWorkYearChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeaPassword
        {
            get
            {
                return _TeaPassword;
            }
            set
            {
                OnTeaPasswordChanging(value);
                ReportPropertyChanging("TeaPassword");
                _TeaPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TeaPassword");
                OnTeaPasswordChanged();
            }
        }
        private global::System.String _TeaPassword;
        partial void OnTeaPasswordChanging(global::System.String value);
        partial void OnTeaPasswordChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudentManageModel", "FK__CourseTea__TeaNu__1FEDB87C", "CourseTeach")]
        public EntityCollection<CourseTeach> CourseTeach
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CourseTeach>("StudentManageModel.FK__CourseTea__TeaNu__1FEDB87C", "CourseTeach");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CourseTeach>("StudentManageModel.FK__CourseTea__TeaNu__1FEDB87C", "CourseTeach", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
