//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ClassLibrary1
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CourseTeach))]
    public partial class Teacher: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public string TeaNum
        {
            get { return _teaNum; }
            set
            {
                if (_teaNum != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“TeaNum”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _teaNum = value;
                    OnPropertyChanged("TeaNum");
                }
            }
        }
        private string _teaNum;
    
        [DataMember]
        public string TeaName
        {
            get { return _teaName; }
            set
            {
                if (_teaName != value)
                {
                    _teaName = value;
                    OnPropertyChanged("TeaName");
                }
            }
        }
        private string _teaName;
    
        [DataMember]
        public string TeaGender
        {
            get { return _teaGender; }
            set
            {
                if (_teaGender != value)
                {
                    _teaGender = value;
                    OnPropertyChanged("TeaGender");
                }
            }
        }
        private string _teaGender;
    
        [DataMember]
        public int TeaAge
        {
            get { return _teaAge; }
            set
            {
                if (_teaAge != value)
                {
                    _teaAge = value;
                    OnPropertyChanged("TeaAge");
                }
            }
        }
        private int _teaAge;
    
        [DataMember]
        public string TeaPhoto
        {
            get { return _teaPhoto; }
            set
            {
                if (_teaPhoto != value)
                {
                    _teaPhoto = value;
                    OnPropertyChanged("TeaPhoto");
                }
            }
        }
        private string _teaPhoto;
    
        [DataMember]
        public Nullable<System.DateTime> TeaWorkYear
        {
            get { return _teaWorkYear; }
            set
            {
                if (_teaWorkYear != value)
                {
                    _teaWorkYear = value;
                    OnPropertyChanged("TeaWorkYear");
                }
            }
        }
        private Nullable<System.DateTime> _teaWorkYear;
    
        [DataMember]
        public string TeaPassword
        {
            get { return _teaPassword; }
            set
            {
                if (_teaPassword != value)
                {
                    _teaPassword = value;
                    OnPropertyChanged("TeaPassword");
                }
            }
        }
        private string _teaPassword;

        #endregion
        #region 导航属性
    
        [DataMember]
        public TrackableCollection<CourseTeach> CourseTeach
        {
            get
            {
                if (_courseTeach == null)
                {
                    _courseTeach = new TrackableCollection<CourseTeach>();
                    _courseTeach.CollectionChanged += FixupCourseTeach;
                }
                return _courseTeach;
            }
            set
            {
                if (!ReferenceEquals(_courseTeach, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("当启用 ChangeTracking 时，无法设置 FixupChangeTrackingCollection");
                    }
                    if (_courseTeach != null)
                    {
                        _courseTeach.CollectionChanged -= FixupCourseTeach;
                        // 这是执行级联删除的关联中的主体端。
                        // 移除当前集合中所有实体的级联删除事件处理程序。
                        foreach (CourseTeach item in _courseTeach)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _courseTeach = value;
                    if (_courseTeach != null)
                    {
                        _courseTeach.CollectionChanged += FixupCourseTeach;
                        // 这是执行级联删除的关联中的主体端。
                        // 为新集合中已存在的所有实体添加级联删除事件处理程序。
                        foreach (CourseTeach item in _courseTeach)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("CourseTeach");
                }
            }
        }
        private TrackableCollection<CourseTeach> _courseTeach;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            CourseTeach.Clear();
        }

        #endregion
        #region 关联修复
    
        private void FixupCourseTeach(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (CourseTeach item in e.NewItems)
                {
                    item.Teacher = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("CourseTeach", item);
                    }
                    // 这是执行级联删除的关联中的主体端。
                    // 更新事件侦听器以引用新依赖。
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CourseTeach item in e.OldItems)
                {
                    if (ReferenceEquals(item.Teacher, this))
                    {
                        item.Teacher = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("CourseTeach", item);
                        // 删除此识别关联的依赖端。如果当前状态为“已添加”，
                        // 则允许更改关系而不会导致删除依赖。
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // 这是执行级联删除的关联中的主体端。
                    // 从事件侦听器中移除前一个依赖。
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion
    }
}
